version: '3.8'

services:

  fittrackee-db:
    container_name: fittrackee-db
    build: ./db
    env_file:
      - .env


  fittrackee:
    container_name: fittrackee
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - fittrackee-db
      - redis
    links:
      - fittrackee-db
      - redis
    volumes:
      - fittrackee_upload:/uploads:rw

  redis:
    container_name: fittrackee-redis
    image: "redis:latest"
    hostname: redis
    ports:
      - 6379:6379

volumes:
  fittrackee_upload:
